### ISSUE TITLE
Received a DELIS ID and DELIS PASSWORD from support, but cannot login.

### ISSUE THREAD

**Issue by gmverdon** [dpdconnect/woocommerce-shipping#13]
Hi, 

I received a DELIS ID and DELIS PASSWORD from support of DPD, but when I use those credentials and want to create a shipping label I get the following error:

Uncaught DpdConnect\Sdk\Exceptions\AuthenticateException: {"code":401,"message":"Bad credentials"}

dpdconnect/vendor/dpdconnect/php-sdk/src/Resources/Authentication.php(58): DpdConnect\Sdk\Common\HttpClient->sendRequest('POST', 'auth/login', false, Array,  '{"username": **mycred...**,

**Comment by dpdplugin** [comment]
Please contact your account manager and ask for DPD Connect credentials.
