### ISSUE TITLE
Setup freeshipping from x euros

### ISSUE THREAD

**Issue by pastekbe** [dpdconnect/woocommerce-shipping#16]
Hi,

Happy new year.
How do you setup free shipping from X euros within this Wordpress extension ? I meant, all your competitors include in their extension different options to do that, yours, not available. My client has a specific setup (free from x euros, different fee if pickup/@home/saturday, different price for each country, etc.)

PS: I already check on DPD Shipping Manager, nothing relevant.

Thanks,
Ludovic.

**Comment by dpdplugin** [comment]
Hi,

The plugin is compatible with most table rates plugin like the official WooCommerce one.
You can use one of those.

**Comment by carambola-jurgen** [comment]
It would be nice to have this using WooCommerce core (as there is flat & free shipping by default)... Official Woo table rate shipping is quite expensive, so otherwise I would need to code that (as I do know to hide the flat options if free is possible)...
