### ISSUE TITLE
missing autoload.php

### ISSUE THREAD

**Issue by Lexime1986** [dpdconnect/woocommerce-shipping#17]
If i try to install this plugin it installs but i cant activate missing vendor/autoload.php

Warning: require_once(vendor/autoload.php): failed to open stream: No such file or directory in /customers/2/d/b/dartspaleis.be/httpd.www/wp-content/plugins/woocommerce-shipping-master/dpdconnect.php on line 3 Fatal error: require_once(): Failed opening required 'vendor/autoload.php' (include_path='.:/usr/share/php') in /customers/2/d/b/dartspaleis.be/httpd.www/wp-content/plugins/woocommerce-shipping-master/dpdconnect.php on line 3

Any advice

**Comment by dpdplugin** [comment]
Hi,

The plugin needs to be downloaded from the releases page, otherwise you will get the development build
