### ISSUE TITLE
Can't activate plugin

### ISSUE THREAD

**Issue by 88aleksandra88** [dpdconnect/woocommerce-shipping#18]
Can't activate the plugin. 
Error message:
Warning: require_once(vendor/autoload.php): failed to open stream: No such file or directory in /home/ocge4930/dev.kitciel.com/wp-content/plugins/woocommerce-shipping/dpdconnect.php on line 3
Fatal error: require_once(): Failed opening required 'vendor/autoload.php' (include_path='.:/opt/alt/php74/usr/share/pear') in /home/ocge4930/dev.kitciel.com/wp-content/plugins/woocommerce-shipping/dpdconnect.php on line 3

**Comment by Brandinwebdesign** [comment]
Here same problem. Hope it will be fixed soon

**Comment by dpdplugin** [comment]
You will need to download the plugin from the releases page, you are currently installing the non prebuild development build.
