### ISSUE TITLE
Need installer Zip file

### ISSUE THREAD

**Issue by lvandenborre** [dpdconnect/woocommerce-shipping#19]
I have tried uploading the zipped content in woocommerce as a new plugin, but vcannot activate it.. missing vendor/Autoupload.php on line 3.
Would it not be easier for you guys to just deliver a plugin zip file that works with Woocommerce? Not all woocommerce users are IT'ers

**Comment by D0nVit0** [comment]
Download the zip file. https://github.com/dpdconnect/woocommerce-shipping/releases/download/1.2.8/dpdconnect.zip 
Upzip the zip. 
Upload the folder /dpdconnect/ to your plugin folder. 
Activate the plugin in the Wordpress backend. 

That should work.
