### ISSUE TITLE
Shipping method title + translation

### ISSUE THREAD

**Issue by carambola-jurgen** [dpdconnect/woocommerce-shipping#21]
The shipping method title as configured in the shipping zones pop up for a specific shipping method is not shown in the front end. 
=> "woocommerce_dpd_pickup_zone_title"

The title as mentioned in the separate "DPD Pickup" / "DPD Home" / ... tab is always shown, no matter what you fill in in the other field above.
=> woocommerce_dpd_pickup_title"

The title you see for the moment (the one from the separate tab) is not appearing in WPML for translation. I had to add this manually to String Translation, then it works
=> (domain) "admin_texts_woocommerce_dpd_pickup_settings"
=> (name) "[woocommerce_dpd_pickup_settings]title"

You should add a "wpml-config.xml " (with all admin texts) in the root of your plugin with a structure like the example below to enable this.
```
<wpml-config>
  <admin-texts>
    <key name="woocommerce_dpd_pickup_settings">
      <key name="title"/>
    </key>
  </admin-texts>
</wpml-config>
```

Of course best solution would be to show the shipping method as configured in the shipping zones pop up (cfr above).

Thanks!

**Comment by dpdplugin** [comment]
The shipping methods in the plugin are deprecated and will be removed in a upcoming version

**Comment by D0nVit0** [comment]
> The shipping methods in the plugin are deprecated and will be removed in a upcoming version

Do you have an estimate when we can expect this upcoming version?
