### ISSUE TITLE
Plugin could not be activated because it caused a fatal error .

### ISSUE THREAD

**Issue by wp-newbiefriendly** [dpdconnect/woocommerce-shipping#22]
When I activate plugin:

Warning : require_once (vendor / autoload.php): failed to open stream: No such file or directory in /var/www/vhosts/******/httpdocs/***********/wp-content/plugins/woocommerce-shipping-master /dpdconnect.php on line 3

Fatal error : require_once (): Failed opening required 'vendor / autoload.php' (include_path = '.: / opt / plesk / php / 7.4 / share / pear') in / var / www / vhosts / ******** / httpdocs / *********** / wp-content / plugins / woocommerce-shipping-master / dpdconnect.php on line 3

Can you help me with this one ?

**Comment by dpdplugin** [comment]
Please see issue #20
