### ISSUE TITLE
Fatal error PSR-4 autoloading

### ISSUE THREAD

**Issue by insitingcom** [dpdconnect/woocommerce-shipping#24]
We're experiencing problems installing the plugin in our Woocommerce application. Apparently there's an issue with autoloading classes via composer (psr-4). This is the exception that we're seeing:

```
Fatal error: Uncaught Error: Class 'DpdConnect\classes\Handlers\Activate' not found in /usr/local/var/www/.../wp-content/plugins/dpdconnect/dpdconnect.php on line 40 
```

- dpdconnect v1.2.9 (https://github.com/dpdconnect/woocommerce-shipping/releases/download/1.2.9/dpdconnect.zip)
- Woocommerce v5.3.1
- Wordpress v5.7.2
- PHP 7.4.21

We've installed the plugin directly from the release page on Github as suggested in other issues.
This problem also occurs in a clean install of Wordpress with Woocommerce and no other plugins.
Tested with all versions from 1.2.0 up to 1.2.9

**Comment by insitingcom** [comment]
Apparently the issue is that the Composer autoload class is called with a relative path inside this plugin:

```php
require_once('vendor/autoload.php');
```

This will cause problems when there's already a composer installation in the root of the project. 
Other Wordpress plugins solve it by requiring the autoload class with an absolute path. 

```
require_once(__DIR__ . '/vendor/autoload.php');
```

This seems to fix the issue for us in our local installation.

**Comment by dpdplugin** [comment]
As this issue is already handled internally with @insitingcom, I will close it on Github
