### ISSUE TITLE
feature suggestions / improvements

### ISSUE THREAD

**Issue by codeagencybe** [dpdconnect/woocommerce-shipping#29]
1. Add credential check in the settings with a "validation" flag under the hood. 
First validate the credentials and only if they are correct, then change the validation flag to true before loading any of the other settings to prevent breaking the WooCommerce shipping settings. 
And this will also help preventing people wasting tons of hours to figure out problems when they seem to be related to the account itself. 

2. Add a field to settings to enter a (custom) meta field name for the package reference. 
By default, the plugin is using the post ID which is unknown to most end-users resulting in labels that are not able to identify to which package they belong. 
Some WooCommerce shops use 3rd party plugins to override the default order ID from WooCommerce for a custom order ID with eg custom prefix and pattern like "SO-2021-00064". 
With a proper meta field, it can be used to override which field value should be put on the label in the reference field

3. Add an option to generate a shipping list (similar to DPD central shipper). 
If you generate labels for 50+ orders, you want the carrier to sign a document to confirm the number of packages that have been collected. 
The plugin does not facilitate this feature and none of the labels nor shipments created via WooCommerce and the DPD API are showing into the DPD central shipper backend.

**Comment by dpdplugin** [comment]
Hi @codeagencybe ,

Thank you for your feedback.
