### ISSUE TITLE
Wrong weight on labels

### ISSUE THREAD

**Issue by VincentLoy** [dpdconnect/woocommerce-shipping#3]
Hello, I'm actually testing the pugin in a development server, and when I generate a new label, the weight is not the good one (I think that it's actually given in **grams** instead of **kilograms**.

I already checked my Woocommerce configuration that is setted to work with **Kg**.
![image](https://user-images.githubusercontent.com/7996741/85456079-e0406c00-b59e-11ea-97ad-7d9d696fb4c9.png)

In my test order, I tried to order two different products : **three products of 1 Kg and one product of 2 Kg**. So this must be a **5Kg order**. And the label is telling me : **Gewicht 0.05 kg**

If you need more info, don't hesitate to let me know.

**Comment by dpdplugin** [comment]
Hi @VincentLoy 
Thank you for reporting this.
This is already a known issue with the new plugin, and we are working on a fix.
Please note that the weight on the label is only visual because the packages are weighted at the depot.
