### ISSUE TITLE
Critical error

### ISSUE THREAD

**Issue by daveloodts** [dpdconnect/woocommerce-shipping#32]
Hi, we're now on version 1.2.8.
I tested the new DPD plugin on a staging website and it all resulted in a bunch of critical errors:

require_once(vendor/autoload.php): failed to open stream: No such file or directory in xxxx/wp-content/plugins/dpdconnect/dpdconnect.php on line 3

Fatal error: require_once(): Failed opening required 'vendor/autoload.php' (include_path='.') in xxxx/dpdconnect/dpdconnect.php on line 3

Notice: is_embed werd verkeerd aangeroepen. Voorwaardelijke query-tags werken niet voordat de query is uitgevoerd. Daarvoor geeft deze altijd 'false' terug. Lees [Foutopsporing in WordPress](https://wordpress.org/support/article/debugging-in-wordpress/) voor meer informatie. (Dit bericht is toegevoegd in versie 3.1.0.) in /xxxx/wp-includes/functions.php on line 5768

Notice: is_search werd verkeerd aangeroepen. Voorwaardelijke query-tags werken niet voordat de query is uitgevoerd. Daarvoor geeft deze altijd 'false' terug. Lees [Foutopsporing in WordPress](https://wordpress.org/support/article/debugging-in-wordpress/) voor meer informatie. (Dit bericht is toegevoegd in versie 3.1.0.) in xxx/wp-includes/functions.php on line 5768

The site is just a regular Kadence Theme; not much customization.
What can the issue here?

And when do you plan to get the DPD plugin on wordpress.org.

**Comment by dpdplugin** [comment]
Goodmorning @daveloodts ,

I looks like you are trying to install the development build, this build lacks the vendor folder.
You can download the correct zip file here: https://github.com/dpdconnect/woocommerce-shipping/releases
We plant to release it on wordpress.org in the near future, but I cannot give you a date yet.

**Comment by daveloodts** [comment]
I'm sorry, got it and working now.
