### ISSUE TITLE
Slow WP Admin & PHP errors

### ISSUE THREAD

**Issue by sanderjn** [dpdconnect/woocommerce-shipping#35]
I'm experiencing major issues with 1.3.4 (I haven't used other versions). The WordPress Admin becomes practically unusable after filling in Login Details (causing 50+s page load). Works fine when deleting Login Details.

Using Query Monitor I can see some PHP errors coming from your plugin:

Undefined array key "token"
Undefined array key 0
Undefined array key 1

**Comment by dpdplugin** [comment]
Hi @sanderjn ,

This means your credentials are not correct or properly configured at DPD's side.
Normally the connection should drop but in some cases (not optimized PHP curl settings) the connection doesn't drop properly which is causing a long timeout.
Please contact us at support@x-interactive.nl with your DPD username.
