### ISSUE TITLE
Problems Eori number since version 1.3.3

### ISSUE THREAD

**Issue by myBNS-Jens** [dpdconnect/woocommerce-shipping#37]
If you got dots (.) separating your Eori numbers and update from  a version lower than 1.3.3 to a version bigger or equal to version 1.3.3, and try to create a label for an order you will get an error's message stating 'DPD connect: UNKNOWN_ERROR'.

**Example:**

- This will fail: BE0123.456.789
- This will succeed: BE0123456789

When I dug deeper in the code I discovered that the bad formatted Eori number trows an 'InvalidResponseException error', in the create function of the Shipment class.

Maybe the Eori number can be formatted when saving the DPD options?
Or maybe check if the Eori number has the correct format when submitting the DPD options?

**Comment by dpdplugin** [comment]
I completely agree with you, thats why its solved in the latest version.
