### ISSUE TITLE
Cannot activate the plugin on Woocemmerce, it fails

### ISSUE THREAD

**Issue by knockiiing** [dpdconnect/woocommerce-shipping#4]
After installing the plugin, the activation fails. It gives following errors: Warning: require_once(vendor/autoload.php): failed to open stream: No such file or directory in /data/sites/web/ocheckercom/www/wp-content/plugins/woocommerce-shipping-master/dpdconnect.php on line 3

Fatal error: require_once(): Failed opening required 'vendor/autoload.php' (include_path='.') in /data/sites/web/ocheckercom/www/wp-content/plugins/woocommerce-shipping-master/dpdconnect.php on line 3

**Comment by dpdplugin** [comment]
Hi.

Please download the plugin from the releases page, the repository is not precompiled and ready for direct installation.
