### ISSUE TITLE
Cannot create labels

### ISSUE THREAD

**Issue by gahia** [dpdconnect/woocommerce-shipping#40]
When trying to create a label, I got this error:

> DPD Connect: System.Web.Services.Protocols.SoapException: Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object. at Dpd.Shipper.PublicApi.Services.ShipmentService.d__75.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at Dpd.Shipper.PublicApi.Services.ShipmentService.d__69.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at Dpd.Shipper.PublicApi.Services.ShipmentService.d__100.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at Dpd.Shipper.PublicApi.Soap.Services.ShipmentService.ShipmentServiceBase.d__7.MoveNext() in C:\Work\DPD-Shipper\Source\Shipper\PublicApi\Soap\Services\ShipmentService\ShipmentServiceBase.cs:line 254 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at Dpd.Shipper.PublicApi.Soap.Common.SyncTaskRunner.<>c__DisplayClass0_0`1.<b__0>d.MoveNext() in C:\Work\DPD-Shipper\Source\Shipper\PublicApi\Soap\Common\SyncTaskRunner.cs:line 27 --- End of inner exception stack trace --- at Dpd.Shipper.PublicApi.Soap.Common.SoapServiceBase.HandleServiceException[T](Exception ex, String nameSpace, Object eventData) in C:\Work\DPD-Shipper\Source\Shipper\PublicApi\Soap\Common\SoapServiceBase.cs:line 363 at Dpd.Shipper.PublicApi.Soap.Services.ShipmentService.ShipmentServiceBase.storeOrdersBase33(String serviceNamespace, String apiEndpointName) in C:\Work\DPD-Shipper\Source\Shipper\PublicApi\Soap\Services\ShipmentService\ShipmentServiceBase.cs:line 133 at Dpd.Shipper.PublicApi.Soap.Services.ShipmentService.ShipmentServiceSoap33.storeOrders(StoreOrders33 storeOrders) in C:\Work\DPD-Shipper\Source\Shipper\PublicApi\Soap\Services\ShipmentService\ShipmentServiceSoap33.asmx.cs:line 47

It seems an error on the service and not on the plugin.

DPD Connect for WooCommerce 1.3.6
WooCommerce 6.5.1
WordPress 6.0
PHP 7.4.25

**Comment by dpdplugin** [comment]
Hi @gahia ,

Please contact us at support@x-interactive.nl with your DPD credentials.
I will close this isssue as it will contain personal information thats not meant for Github.
