### ISSUE TITLE
Plugin failed to activate

### ISSUE THREAD

**Issue by CptGunar** [dpdconnect/woocommerce-shipping#41]
Warning: require_once(vendor/autoload.php): failed to open stream: No such file or directory in /data/sites/web/sitename/wp-content/plugins/woocommerce-shipping-master/dpdconnect.php on line 3

Fatal error: require_once(): Failed opening required 'vendor/autoload.php' (include_path='.') in /data/sites/web/sitename/wp-content/plugins/woocommerce-shipping-master/dpdconnect.php on line 3

Upon activating the plugin for woocommerce, I got this error message.

**Comment by hairyken** [comment]
You probably uploaded the source code zip as a plugin to Wordpress.

You should either:
- use composer to create the vendor directory, then package the files in a new zip
- download the latest release [here](https://github.com/dpdconnect/woocommerce-shipping/releases)

Would be handy if the plugin was available via wordpress plugin library, though

**Comment by dpdplugin** [comment]
That is indeed the problem thanks @hairyken.
We agree with you and we are working on that.
