### ISSUE TITLE
Slow loading on Order Page

### ISSUE THREAD

**Issue by jeroen-wiljeonline** [dpdconnect/woocommerce-shipping#51]
Page loading is very slow when accessing the Order page on WooCommerce 7.1.0 with DPD Connect 1.4.2. When the DPD plugin is deactivated, loading is almost instant.

**Comment by dpdplugin** [comment]
Hi @jeroen-wiljeonline it looks like the DPD plugin is trying to connect to DPD but something is not working out.
Could you contact us at support@x-interactive.nl with your DPD username?
