### ISSUE TITLE
Cannot activate plugin

### ISSUE THREAD

**Issue by nealzie** [dpdconnect/woocommerce-shipping#54]
Activating causes fatal error:
Warning: require_once(vendor/autoload.php): failed to open stream: No such file or directory in /mnt/customers-2/customers-el-4453752-42599-reedin-wordpress-pvc-6388785dc9c2ad0020db8d6d/wp-content/wp-content/plugins/woocommerce-shipping-master/dpdconnect.php on line 3 Fatal error: require_once(): Failed opening required 'vendor/autoload.php' (include_path='.:/usr/share/php7') in /mnt/customers-2/customers-el-4453752-42599-reedin-wordpress-pvc-6388785dc9c2ad0020db8d6d/wp-content/wp-content/plugins/woocommerce-shipping-master/dpdconnect.php on line 3

**Comment by dpdplugin** [comment]
This is expected behaviour since a composer vendor folder contains compiled code.
You can download an installable zip on the releases page.
https://github.com/dpdconnect/woocommerce-shipping/releases
