### ISSUE TITLE
problems with woocommerce

### ISSUE THREAD

**Issue by jev64** [dpdconnect/woocommerce-shipping#60]
When I install this plugin I have on several woocommerce websites the same error, the pay button is gone.
after disableing the DPD plugin all is working fine
Please help us out

**Comment by jev64** [comment]
Notice: Undefined offset: 0 in /home/u123936p127826/domains/janeverts.com/public_html/online/wp-content/plugins/dpdconnect/classes/Handlers/Pickup.php on line 41

Notice: Undefined offset: 1 in /home/u123936p127826/domains/janeverts.com/public_html/online/wp-content/plugins/dpdconnect/classes/shippingmethods/DPDShippingMethod.php on line 44

**Comment by jev64** [comment]
you can also see this video of the party who checked this for us
https://www.loom.com/share/6b24cbefe7834c6cbeb64e7458a8795d

**Comment by nemovich** [comment]
Having similar issue with the pay button disappearing while DPD plugin is activated, error message :

`PHP Notice:  Trying to access array offset on value of type null in ***path_removed***/public_html/wp-content/plugins/dpdconnect/classes/Handlers/Pickup.php on line 200`

**Comment by nemovich** [comment]
I was having the same issue, I checked the log an it said that the credentials were wrong. I put the right ones and the problem is fixed. I don't know if it's the same for you.

**Comment by jev64** [comment]
> I was having the same issue, I checked the log and it said that the credentials were wrong. I put the right ones and the problem was fixed. I don't know if it's the same for you.

Thank you I was only testing not filled in the credentials yet. But only the install created the issues. The fact that I didn';t yet filled in the credentials can't be that a plugin creates such issues. At the moment I only have virtual products but i was looking if this plugin creates issues before a definite choice. But it does..

**Comment by nemovich** [comment]
> > I was having the same issue, I checked the log and it said that the credentials were wrong. I put the right ones and the problem was fixed. I don't know if it's the same for you.
> 
> Thank you I was only testing not filled in the credentials yet. But only the install created the issues. The fact that I didn';t yet filled in the credentials can't be that a plugin creates such issues. At the moment I only have virtual products but i was looking if this plugin creates issues before a definite choice. But it does..

This plugin relies heavely on the DPD server to fetch data and assumes you have everything set up in settings beforehand (author may confirm this).

**Comment by jev64** [comment]
> > > I was having the same issue, I checked the log and it said that the credentials were wrong. I put the right ones and the problem was fixed. I don't know if it's the same for you.
> > 
> > 
> > Thank you I was only testing not filled in the credentials yet. But only the install created the issues. The fact that I didn';t yet filled in the credentials can't be that a plugin creates such issues. At the moment I only have virtual products but i was looking if this plugin creates issues before a definite choice. But it does..
> 
> This plugin relies heavely on the DPD server to fetch data and assumes you have everything set up in settings beforehand (author may confirm this).

That may be the case but is insain that only the installation of the plugin (and activation) directly causes issues. at that moment you don't even had the change to fill in the credentials. A plugin must never creates issues even if you did not filled in the credentials yet. 

Thans for reacting on this. @dpdplugin is a bit quiet....

**Comment by dpdplugin** [comment]
For the plugin to work you need indeed proper credentials. If you add dpd shipping methods and the plugin cannot connect to DPD because wrong or not properly configured credentials it will not work.
