### ISSUE TITLE
For the plugin to work you need indeed proper credentials. If you add dpd shipping methods and the plugin cannot connect to DPD because wrong or not properly configured credentials it will not work.

### ISSUE THREAD

**Issue by jev64** [dpdconnect/woocommerce-shipping#63]
For the plugin to work you need indeed proper credentials. If you add dpd shipping methods and the plugin cannot connect to DPD because wrong or not properly configured credentials it will not work.

_Originally posted by @dpdplugin in https://github.com/dpdconnect/woocommerce-shipping/issues/60#issuecomment-1580986080_

**Comment by jev64** [comment]
I don't understand why you closed the issue.

It is totally wrong to have a plugin crash my woocommerce site if i don't fill in the credentials. It should not interfere with woocommerce, it would not work if you don't fill in the credentials that I agree, but at the moment you install the plugin woocommerce crashes. I suggest that DPD changes that way of working, this is bad programming.
So you say also if there is no connection with the DPD server, which I can't help if it is a internet error or even an dpd error my clients even if they buy a virtual product can pay anymore???

**Comment by dpdplugin** [comment]
The issue was closed because the problem was solved, aka the plugin was not properly configured.
We are aware things can be improved.
I will therefore closing this issue as well
