### ISSUE TITLE
Error installing plugin

### ISSUE THREAD

**Issue by versleverancier** [dpdconnect/woocommerce-shipping#64]
Installed both plugins to start with DPD

Warning: require_once(vendor/autoload.php): Failed to open stream: No such file or directory in /customers/4/1/4/versleverancier.be/httpd.www/wp-content/plugins/woocommerce-shipping-1.4.4/dpdconnect.php on line 3 Fatal error: Uncaught Error: Failed opening required 'vendor/autoload.php' (include_path='.:/usr/share/php') in /customers/4/1/4/versleverancier.be/httpd.www/wp-content/plugins/woocommerce-shipping-1.4.4/dpdconnect.php:3 Stack trace: #0 /customers/4/1/4/versleverancier.be/httpd.www/wp-admin/includes/plugin.php(2314): include_once() #1 /customers/4/1/4/versleverancier.be/httpd.www/wp-admin/plugins.php(192): plugin_sandbox_scrape('woocommerce-shi...') #2 {main} thrown in /customers/4/1/4/versleverancier.be/httpd.www/wp-content/plugins/woocommerce-shipping-1.4.4/dpdconnect.php on line 3

This error occures, the file is in this directory

**Comment by dpdplugin** [comment]
Hi,

You are trying to install the precompiled version, please delete the currently installed plugin and download the plugin again here: https://github.com/dpdconnect/woocommerce-shipping/releases

**Comment by versleverancier** [comment]
Hi,
We installed version 1.4.4 from December several times, and deleted the previous version. We were able to install the dpd connect plugin, but the shipping 1.4.4 plugin gives us the error that I'm mentioning

**Comment by dpdplugin** [comment]
But did you install the plugin from the releases tab, in the error I can see the precompiled version is installed.
For 1.4.4 you need this zip file: https://github.com/dpdconnect/woocommerce-shipping/releases/download/1.4.4/dpdconnect.zip

**Comment by versleverancier** [comment]
We installed the file from your link , than after this we tried to install the woocommerce shipping master plugin and we get the same error as above.

**Comment by dpdplugin** [comment]
Could you contact us at support@x-interactive.nl with your DPD username?
Il look further into it.
