### ISSUE TITLE
Create table queries are run on every construct of the plugin.

### ISSUE THREAD

**Issue by BernardV** [dpdconnect/woocommerce-shipping#67]
The Activate::handle() is called every time the plugin is loaded and it calls self::updateDb();
https://github.com/dpdconnect/woocommerce-shipping/blob/master/classes/Handlers/Activate.php#L10

It should only be called on activation of the plugin. Now the database is hammered with CREATE TABLE calls.

**Comment by dpdplugin** [comment]
Thanks for pointing this out, we will change it in the next release.
