### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined method `WP_Post::get_id()` in `classes/Handlers/DownloadLabelBox.php:32`

### ISSUE THREAD

**Issue by remcotolsma** [dpdconnect/woocommerce-shipping#71]
We just tested version `1.4.5` on WordPress `6.3.2`:

```
Fatal error: Uncaught Error: Call to undefined method WP_Post::get_id() in public_html/wp-content/plugins/dpdconnect/classes/Handlers/DownloadLabelBox.php:32
Stack trace:
#0 public_html/wp-admin/includes/template.php(1443): DpdConnect\classes\Handlers\DownloadLabelBox::render()
#1 public_html/wp-admin/edit-form-advanced.php(681): do_meta_boxes()
#2 public_html/wp-admin/post.php(206): require('/home/moosefarg...')
#3 {main}
thrown in public_html/wp-content/plugins/dpdconnect/classes/Handlers/DownloadLabelBox.php on line 32
```

https://github.com/dpdconnect/woocommerce-shipping/blob/0dd68cba99e82dce66bdaabb15f2547cf0ff4c06/classes/Handlers/DownloadLabelBox.php#L25-L60

It looks like the plugin assume that HPOS is always enabled? We handle this as follows in our plugins:

https://github.com/pronamic/pronamic-order-referrer-for-woocommerce/blob/08b81d4fbdc643a85d2444d27a989bb0499d8d26/src/Plugin.php#L119-L148

```php
	/**
	 * Maybe add a meta box the WooCommerce order.
	 * 
	 * @link https://github.com/pronamic/wp-pronamic-pay-woocommerce/issues/41
	 * @link https://developer.wordpress.org/reference/hooks/add_meta_boxes/
	 * @param string           $post_type_or_screen_id Post type or screen ID.
	 * @param WC_Order|WP_Post $post_or_order_object   Post or order object.
	 * @return void
	 */
	public function maybe_add_meta_box_to_wc_order( $post_type_or_screen_id, $post_or_order_object ) {
		if ( ! \in_array( $post_type_or_screen_id, [ 'shop_order', 'woocommerce_page_wc-orders' ], true ) ) {
			return;
		}

		$order = $post_or_order_object instanceof WC_Order ? $post_or_order_object : \wc_get_order( $post_or_order_object->ID );

		if ( ! $order instanceof WC_Order ) {
			return;
		}

		\add_meta_box(
			'pronamic-woocommerce-order-referrer',
			\__( 'Referrers', 'pronamic-order-referrer-for-woocommerce' ),
			function () use ( $order ) {
				include __DIR__ . '/../views/admin-meta-box-woocommerce-order.php';
			},
			$post_type_or_screen_id,
			'normal'
		);
	}
```

Related to:

- https://github.com/dpdconnect/woocommerce-shipping/issues/69

**Comment by dpdplugin** [comment]
Thanks for the info.
As your client has already started an internal ticket with us I will close this one.

**Comment by remcotolsma** [comment]
@dpdplugin is it also possible to only close the issues once it has been resolved in the codebase of this repository? Then it will be easier for us and others to follow. I had mentioned this before, but received no response:

> Is it more convenient to only close these issues once the problem has actually been resolved in the codebase?

- https://github.com/dpdconnect/woocommerce-shipping/issues/68
