### ISSUE TITLE
Slowing down website

### ISSUE THREAD

**Issue by art-n** [dpdconnect/woocommerce-shipping#77]
Fresh install
WordPress 6.5.5
PHP 8.1.0
DPD 1.4.6

**Comment by Fanna1119** [comment]
Also having this issue, takes around 5 minutes just to load up a admin page

**Comment by basserd** [comment]
I'm also having this issue the plugin is not usable right now!

**Comment by art-n** [comment]
New 1.4.7 release is just getting a fatal error on activation.

**Comment by dpdplugin** [comment]
Hi @art-n!
This issue could happen when the credentials you used for the plug-in are invalid.
The best thing to do in this case is to either contact us or DPD directly to check the credentials.

Note that you should fill in your Delis ID & Delis password, these should have been delivered by DPD.
