### ISSUE TITLE
The title of the shippingmethod is not translatable

### ISSUE THREAD

**Issue by Essec-Jens** [dpdconnect/woocommerce-shipping#8]
This title of the shippingmethod shown in the shippingzones is not translatable, not with the plugin and not even with a translation plugin.

This is something that could be a must for some websites.

**Comment by mediavinc** [comment]
I agree. We have the same issue : the custom name we gave to the shipping method does not apply. It is not convenient to keep a shipping method that display only "Predict"... WooCommerce allows us to rename each shipping method but it does not work for your plugin...

**Comment by dpdplugin** [comment]
The shipping methods are deprecated and will be removed in an upcoming version.
The newest versions of the plugin are compatible with all shipping methods.
