### ISSUE TITLE
Fatal error while activating this plugin

### ISSUE THREAD

**Issue by yulumadavid** [dpdconnect/woocommerce-shipping#80]
When activating this plugin for a site on a server with php 8.3 the activation was cancelled due to a fatal:
![image](https://github.com/user-attachments/assets/5b9c70f1-8fba-46a8-9683-67e16f755ab9)

when debugging, this is the error:

`[16-Sep-2024 07:41:16 UTC] PHP Warning:  require_once(vendor/autoload.php): Failed to open stream: No such file or directory in /wp-content/plugins/woocommerce-shipping-master/dpdconnect.php on l>[16-Sep-2024 07:41:16 UTC] PHP Fatal error:  Uncaught Error: Failed opening required 'vendor/autoload.php' (include_path='.:/usr/share/php') in /wp-content/plugins/woocommerce-shipping-master/dpd>Stack trace:
#0 /wp-admin/includes/plugin.php(2387): include_once()
#1 /wp-admin/includes/plugin.php(673): plugin_sandbox_scrape()
#2 /wp-admin/plugins.php(60): activate_plugin()
#3 {main}
  thrown in /wp-content/plugins/woocommerce-shipping-master/dpdconnect.php on line 3`

**Comment by rvdsteege** [comment]
Looks like you downloaded the plugin source code, instead of the release from https://github.com/dpdconnect/woocommerce-shipping/releases/tag/1.4.7? The release includes the `vendor/autoload.php` file.

**Comment by dpdplugin** [comment]
Hi @yulumadavid!
This issue happens when you download the source code like @rvdsteege mentioned.
When you download the plug-in from the releases tab this should be resolved.
